FROM jenkins/jenkins:lts

USER root

# Install Maven
RUN apt-get update && apt-get install -y maven

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

# Install Docker CLI
RUN apt-get install -y docker.io

# Fix Docker socket permission
RUN usermod -aG docker jenkins

USER jenkins